(("name" . "chez-stats-test")
("version" . "0.0.1")
("description" . "")
("keywords")
("author" 
    ("hinkelman"))
("private" . #f)
("scripts")
("dependencies")
("repl" . "scheme")
("run" . "scheme --script"))
