(("name" . "chez-stats")
("version" . "0.4.0")
("description" . "Procedures for basic descriptive statistics and generating random variates in Chez Scheme.")
("keywords")
("author" 
    ("hinkelman"))
("private" . #f)
("scripts")
("dependencies")
("devDependencies"))
